# Generated by Django 2.2.10 on 2020-02-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.BigIntegerField()),
            ],
        ),
    ]
